
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - math.a-ksy
  resources:
  - operands
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - math.a-ksy
  resources:
  - operands/finalizers
  verbs:
  - update
- apiGroups:
  - math.a-ksy
  resources:
  - operands/status
  verbs:
  - get
  - patch
  - update
